name: Scheduled News Scraper

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour on the hour
  workflow_dispatch:  # Allows you to trigger the workflow manually

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Allows the workflow to write to the repository

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history so we can access previous files

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run News Scraper
        run: python news_scraper.py

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add news_archive.json new_articles.json
          git commit -m "Update news data [skip ci]" || echo "No changes to commit"
          git push
