name: Scheduled News Scraper and Stock Analyzer

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour on the hour
    #- cron: '*/10 * * * *'  # Runs every 10 minutes
  workflow_dispatch:  # Allows you to trigger the workflow manually

jobs:
  scrape_and_analyze:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Allows the workflow to write to the repository

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history so we can access previous files

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pandas openai

      - name: Run News Scraper and Analyzer
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python news_scraper.py

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add news_archive.json new_articles.json stock_news_analysis.json stock_news_mapping.json
          git commit -m "Update news and stock analysis [skip ci]" || echo "No changes to commit"
          git push
